<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>org.nervousync</groupId>
	<artifactId>brain</artifactId>
	<version>1.0.0</version>
	<url>https://nervousync.org/projects/brain/index.shtml</url>
	<name>Nervousync Brain Data Source Module</name>
	<description>
		Brain Java Data Source Package, support database/table sharding, remote schema supported (Restful/SOAP etc.)
	</description>
	<issueManagement>
		<url>https://github.com/wmkm0113/brain/issues</url>
		<system>Github Issues</system>
	</issueManagement>
	<scm>
		<tag>v1.0.0</tag>
		<url>https://github.com/wmkm0113/brain</url>
		<connection>scm:git:https://github.com/wmkm0113/brain.git</connection>
		<developerConnection>scm:git:https://github.com/wmkm0113/brain.git</developerConnection>
	</scm>
	<licenses>
		<license>
			<name>The Apache Software License, Version 2.0</name>
			<url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
			<distribution>repo</distribution>
		</license>
	</licenses>
	<organization>
		<url>https://nervousync.org/</url>
		<name>Nervousync Studio</name>
	</organization>
	<developers>
		<developer>
			<name>Steven Wee</name>
			<email>wmkm0113@gmail.com</email>
			<url>https://nervousync.org/member/wmkm0113</url>
			<organization>Nervousync Studio</organization>
			<organizationUrl>https://nervousync.org/index.shtml</organizationUrl>
		</developer>
	</developers>
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.version>3.15.0</maven.compiler.version>
		<maven.jar.version>3.5.0</maven.jar.version>
		<maven.surefire.version>3.5.4</maven.surefire.version>
		<maven.resource.version>3.4.0</maven.resource.version>
		<maven.source.version>3.4.0</maven.source.version>
		<maven.javadoc.version>3.12.0</maven.javadoc.version>
		<maven.gpg.version>3.2.8</maven.gpg.version>
		<maven.compiler.source>11</maven.compiler.source>
		<maven.compiler.target>11</maven.compiler.target>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<junit.jupiter.version>5.14.2</junit.jupiter.version>
		<jakarta.annotation.version>2.1.1</jakarta.annotation.version>
		<nervousync.utils.version>1.3.0.1</nervousync.utils.version>
		<jersey.version>3.1.11</jersey.version>
		<hk2.version>3.1.1</hk2.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter</artifactId>
			<version>${junit.jupiter.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>jakarta.persistence</groupId>
			<artifactId>jakarta.persistence-api</artifactId>
			<version>3.1.0</version>
		</dependency>
		<dependency>
			<groupId>jakarta.xml.ws</groupId>
			<artifactId>jakarta.xml.ws-api</artifactId>
			<version>3.0.1</version>
		</dependency>
		<dependency>
			<groupId>jakarta.annotation</groupId>
			<artifactId>jakarta.annotation-api</artifactId>
			<version>${jakarta.annotation.version}</version>
		</dependency>
		<!-- Utils -->
		<dependency>
			<groupId>org.nervousync</groupId>
			<artifactId>utils-all</artifactId>
			<version>${nervousync.utils.version}</version>
		</dependency>
		<!-- Jersey Support -->
		<dependency>
			<groupId>org.glassfish.jersey.core</groupId>
			<artifactId>jersey-common</artifactId>
			<version>${jersey.version}</version>
			<exclusions>
				<exclusion>
					<groupId>jakarta.ws.rs</groupId>
					<artifactId>jakarta.ws.rs-api</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.glassfish.hk2</groupId>
			<artifactId>hk2-api</artifactId>
			<version>${hk2.version}</version>
			<exclusions>
				<exclusion>
					<groupId>org.glassfish.hk2</groupId>
					<artifactId>hk2-utils</artifactId>
				</exclusion>
				<exclusion>
					<groupId>jakarta.inject</groupId>
					<artifactId>jakarta.inject-api</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.glassfish.hk2</groupId>
			<artifactId>hk2-locator</artifactId>
			<version>${hk2.version}</version>
			<exclusions>
				<exclusion>
					<groupId>org.javassist</groupId>
					<artifactId>javassist</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.glassfish.hk2</groupId>
					<artifactId>hk2-utils</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.glassfish.hk2</groupId>
					<artifactId>hk2-api</artifactId>
				</exclusion>
				<exclusion>
					<groupId>jakarta.inject</groupId>
					<artifactId>jakarta.inject-api</artifactId>
				</exclusion>
				<exclusion>
					<groupId>jakarta.annotation</groupId>
					<artifactId>jakarta.annotation-api</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.glassfish.hk2</groupId>
			<artifactId>hk2-utils</artifactId>
			<version>${hk2.version}</version>
			<exclusions>
				<exclusion>
					<groupId>jakarta.inject</groupId>
					<artifactId>jakarta.inject-api</artifactId>
				</exclusion>
				<exclusion>
					<groupId>jakarta.annotation</groupId>
					<artifactId>jakarta.annotation-api</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.glassfish.jersey.inject</groupId>
			<artifactId>jersey-hk2</artifactId>
			<version>${jersey.version}</version>
			<exclusions>
				<exclusion>
					<groupId>org.glassfish.jersey.core</groupId>
					<artifactId>jersey-common</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.glassfish.hk2</groupId>
					<artifactId>hk2-locator</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.glassfish.jersey.core</groupId>
			<artifactId>jersey-client</artifactId>
			<version>${jersey.version}</version>
			<exclusions>
				<exclusion>
					<groupId>jakarta.ws.rs</groupId>
					<artifactId>jakarta.ws.rs-api</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>${maven.compiler.version}</version>
				<configuration>
					<source>${maven.compiler.source}</source>
					<target>${maven.compiler.target}</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<version>${maven.jar.version}</version>
				<configuration>
					<archive>
						<manifest>
							<addDefaultImplementationEntries>true</addDefaultImplementationEntries>
							<addDefaultSpecificationEntries>true</addDefaultSpecificationEntries>
							<addClasspath>true</addClasspath>
						</manifest>
						<manifestEntries>
							<Built-By>${project.organization.name}</Built-By>
							<Build-Jdk>${java.vm.name} ${java.vendor.version} (${java.runtime.version})</Build-Jdk>
							<Implementation-Vendor-Id>${project.groupId}</Implementation-Vendor-Id>
						</manifestEntries>
					</archive>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>${maven.surefire.version}</version>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-javadoc-plugin</artifactId>
				<version>${maven.javadoc.version}</version>
				<executions>
					<execution>
						<phase>package</phase>
						<id>attach-javadocs</id>
						<goals>
							<goal>jar</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<javadocExecutable>${java.home}/bin/javadoc</javadocExecutable>
					<doclint>-html</doclint>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-resources-plugin</artifactId>
				<version>${maven.resource.version}</version>
				<configuration>
					<encoding>UTF-8</encoding>
					<nonFilteredFileExtensions>
						<nonFilteredFileExtension>xsd</nonFilteredFileExtension>
					</nonFilteredFileExtensions>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-source-plugin</artifactId>
				<version>${maven.source.version}</version>
				<executions>
					<execution>
						<phase>package</phase>
						<id>attach-sources</id>
						<goals>
							<goal>jar-no-fork</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
	<profiles>
		<profile>
			<id>release</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.sonatype.central</groupId>
						<artifactId>central-publishing-maven-plugin</artifactId>
						<version>0.10.0</version>
						<extensions>true</extensions>
						<configuration>
							<publishingServerId>OSS</publishingServerId>
						</configuration>
					</plugin>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-gpg-plugin</artifactId>
						<version>${maven.gpg.version}</version>
						<executions>
							<execution>
								<id>sign-artifacts</id>
								<phase>verify</phase>
								<goals>
									<goal>sign</goal>
								</goals>
								<configuration>
									<executable>gpg</executable>
									<keyname>${gpg.keyname}</keyname>
								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
</project>